org: mahen
app: testing-serverless
service: sls-whatsapp
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

frameworkVersion: '>=1.5.3'

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  logRetentionInDays: 30
  stackTags:
    Environment: ${self:provider.stage}
    Product: whatsapp
  iamRoleStatements:
  - Effect: Allow
    Action: [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents"
    ]
    Resource: "*"

functions:
  processMessage:
    handler: 'src/handlers/processMessage.receiveMessage'
    package:
      include:
        - src/controller/botResponse.js
        - src/utils/botDictionary.js
        - src/utils/responselist.json
    events:
      - http:
          integration: lambda
          path: webhook
          method: post
          cors: true
          response:
            headers:
              Content-Type: "'text/xml; charset=utf-8'"
